spring:

  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update
    open-in-view: off
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: p0stgres@2o22
    url: "jdbc:postgresql://localhost:5432/students"
#    hikari:
#      auto-commit: false
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 200MB
#      max-request-size: 205MB
#      file-size-threshold: 2KB
#server:
#  error:
#    whitelabel:
#      enabled: false
#    path: "/error"
#

